name: CI-CD
on:
  push:
    branches: [ "main" ]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Run unit tests
        run: go test -v ./...

      - name: Build Docker image
        run: docker build -t gcr.io/$GCP_PROJECT/transaction-app:${{ github.sha }} .

      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Push image to GCR
        run: docker push gcr.io/$GCP_PROJECT/transaction-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: gcr.io/$GCP_PROJECT/transaction-app:${{ github.sha }}
          service: transaction-service
          region: us-central1
          project_id: ${{ secrets.GCP_PROJECT }}
