name: GCP Demo CI/CD

on:
  push:
    branches: [ main ]

env:
  TF_WORKING_DIR: terraform
  IMAGE_NAME: go-server-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1. Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Install Cloud SDK (and kubectl)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'
          install_components: 'gke-gcloud-auth-plugin,kubectl'  # <-- comma-separated string

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build & push Docker image
        id: docker
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${IMAGE_NAME}:${TAG}
          docker build -t $IMAGE go-server-demo/
          docker push $IMAGE
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -upgrade

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="image=${{ steps.docker.outputs.image }}"
