# .github/workflows/terraform-destroy.yml
name: Destroy Infrastructure

# This workflow can be triggered manually from the GitHub UI
on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: terraform

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -upgrade

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform destroy -auto-approve -lock=false \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="oauth_client_id=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}"
